import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

// Adds CMS-editable copy fields for homepage sections that were previously
// hardcoded: the "Who we are" block, the Featured Tours filter-tab label, and
// the Testimonials section header. (The currencies table from the autogenerated
// diff was removed here — it ships in 20260630_120000_currencies_collection.)
export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "site_settings" ADD COLUMN "homepage_who_we_are_enabled" boolean DEFAULT true;
  ALTER TABLE "site_settings" ADD COLUMN "homepage_who_we_are_heading" varchar;
  ALTER TABLE "site_settings" ADD COLUMN "homepage_who_we_are_title" varchar;
  ALTER TABLE "site_settings" ADD COLUMN "homepage_who_we_are_body" varchar;
  ALTER TABLE "site_settings" ADD COLUMN "homepage_who_we_are_action_label" varchar;
  ALTER TABLE "site_settings" ADD COLUMN "homepage_who_we_are_action_href" varchar;
  ALTER TABLE "site_settings" ADD COLUMN "homepage_featured_tours_tab_label" varchar;
  ALTER TABLE "site_settings" ADD COLUMN "homepage_testimonials_eyebrow" varchar;
  ALTER TABLE "site_settings" ADD COLUMN "homepage_testimonials_title" varchar;
  ALTER TABLE "site_settings" ADD COLUMN "homepage_testimonials_subtitle" varchar;`)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "site_settings" DROP COLUMN "homepage_who_we_are_enabled";
  ALTER TABLE "site_settings" DROP COLUMN "homepage_who_we_are_heading";
  ALTER TABLE "site_settings" DROP COLUMN "homepage_who_we_are_title";
  ALTER TABLE "site_settings" DROP COLUMN "homepage_who_we_are_body";
  ALTER TABLE "site_settings" DROP COLUMN "homepage_who_we_are_action_label";
  ALTER TABLE "site_settings" DROP COLUMN "homepage_who_we_are_action_href";
  ALTER TABLE "site_settings" DROP COLUMN "homepage_featured_tours_tab_label";
  ALTER TABLE "site_settings" DROP COLUMN "homepage_testimonials_eyebrow";
  ALTER TABLE "site_settings" DROP COLUMN "homepage_testimonials_title";
  ALTER TABLE "site_settings" DROP COLUMN "homepage_testimonials_subtitle";`)
}
