/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'product-categories': ProductCategory;
    attractions: Attraction;
    destinations: Destination;
    partners: Partner;
    tours: Tour;
    cruises: Cruise;
    'car-rentals': CarRental;
    customers: Customer;
    bookings: Booking;
    'custom-inquiries': CustomInquiry;
    posts: Post;
    'team-members': TeamMember;
    'site-settings': SiteSetting;
    navigation: Navigation;
    comments: Comment;
    reviews: Review;
    promotions: Promotion;
    payments: Payment;
    'affiliate-clicks': AffiliateClick;
    currencies: Currency;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'product-categories': ProductCategoriesSelect<false> | ProductCategoriesSelect<true>;
    attractions: AttractionsSelect<false> | AttractionsSelect<true>;
    destinations: DestinationsSelect<false> | DestinationsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    tours: ToursSelect<false> | ToursSelect<true>;
    cruises: CruisesSelect<false> | CruisesSelect<true>;
    'car-rentals': CarRentalsSelect<false> | CarRentalsSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    'custom-inquiries': CustomInquiriesSelect<false> | CustomInquiriesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    promotions: PromotionsSelect<false> | PromotionsSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    'affiliate-clicks': AffiliateClicksSelect<false> | AffiliateClicksSelect<true>;
    currencies: CurrenciesSelect<false> | CurrenciesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor' | 'sales';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  status: 'uploading' | 'processing' | 'ready' | 'failed';
  r2Key?: string | null;
  publicUrl?: string | null;
  variants?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  processingError?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories".
 */
export interface ProductCategory {
  id: number;
  title: string;
  slug: string;
  type: 'tour' | 'car-rental' | 'guide' | 'shared';
  sortWeight?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attractions".
 */
export interface Attraction {
  id: number;
  title: string;
  slug: string;
  destination: number | Destination;
  summary?: string | null;
  featuredImage?: (number | null) | Media;
  categories?: (number | ProductCategory)[] | null;
  sortWeight?: number | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations".
 */
export interface Destination {
  id: number;
  title: string;
  /**
   * URL-friendly identifier, e.g. hoi-an
   */
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  summary?: string | null;
  featuredImage?: (number | null) | Media;
  heroImage?: (number | null) | Media;
  region?: ('central' | 'north' | 'south') | null;
  bestTimeToVisit?: string | null;
  hubIntro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  sortWeight?: number | null;
  featuredTours?: (number | Tour)[] | null;
  featuredCarRentals?: (number | CarRental)[] | null;
  featuredGuides?: (number | Post)[] | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tours".
 */
export interface Tour {
  id: number;
  title: string;
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  destination: number | Destination;
  durationDays?: number | null;
  durationText?: string | null;
  routeSummary?: string | null;
  startEnd?: string | null;
  travelStyle?: string | null;
  guideLanguages?: string | null;
  mapImage?: (number | null) | Media;
  highlightIntro?: string | null;
  highlights?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  inclusions?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  exclusions?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  groupSizeMin?: number | null;
  groupSizeMax?: number | null;
  categories?: (number | ProductCategory)[] | null;
  attractions?: (number | Attraction)[] | null;
  ratingAverage?: number | null;
  ratingCount?: number | null;
  isFeatured?: boolean | null;
  sortWeight?: number | null;
  operationType: 'self-operated' | 'partner' | 'hybrid';
  partner?: (number | null) | Partner;
  minPax?: number | null;
  currentPax?: number | null;
  tourType: 'free-walking' | 'free-cycling' | 'paid-private' | 'paid-group' | 'adventure' | 'family' | 'cultural';
  season?: ('summer' | 'winter' | 'year-round') | null;
  isFeaturedInSeason?: boolean | null;
  status: 'active' | 'seasonal' | 'sold-out' | 'paused';
  priceFrom?: number | null;
  currency?: string | null;
  pricingTiers?:
    | {
        label: string;
        price: number;
        minPax?: number | null;
        maxPax?: number | null;
        id?: string | null;
      }[]
    | null;
  availableDates?:
    | {
        date: string;
        id?: string | null;
      }[]
    | null;
  itinerary?:
    | {
        time?: string | null;
        location?: string | null;
        distance?: string | null;
        title?: string | null;
        activity?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        note?: string | null;
        included?:
          | {
              item: string;
              id?: string | null;
            }[]
          | null;
        hotelName?: string | null;
        hotelStars?: number | null;
        hotelRoom?: string | null;
        id?: string | null;
      }[]
    | null;
  addOns?: (number | Partner)[] | null;
  /**
   * Short Q&A pairs surfaced to travellers and emitted as FAQPage structured data for AI/search engines.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  logo?: (number | null) | Media;
  description?: string | null;
  partnerType: 'tour-outsource' | 'spa' | 'dental' | 'nail' | 'wellness' | 'other';
  location?: (number | null) | Destination;
  /**
   * Affiliate commission as a decimal. 0.2 = 20%.
   */
  commissionRate?: number | null;
  contactPerson?: string | null;
  phone?: string | null;
  email?: string | null;
  whatsapp?: string | null;
  rating?: number | null;
  isFeatured?: boolean | null;
  inquiryFormUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "car-rentals".
 */
export interface CarRental {
  id: number;
  title: string;
  slug: string;
  destination: number | Destination;
  routeFrom: string;
  routeTo: string;
  vehicleType: 'sedan' | 'suv' | 'van' | 'luxury' | 'minibus';
  durationText?: string | null;
  priceFrom?: number | null;
  currency?: string | null;
  featuredImage?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  partner?: (number | null) | Partner;
  status: 'active' | 'paused';
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  featuredImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  status: 'draft' | 'published' | 'archived';
  destination?: (number | null) | Destination;
  guideCategory?: ('eat' | 'drink' | 'do' | 'shop' | 'before-trip' | 'service' | 'general') | null;
  attractions?: (number | Attraction)[] | null;
  sortWeight?: number | null;
  relatedTour?: (number | null) | Tour;
  relatedPosts?: (number | Post)[] | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Author display name
   */
  author?: string | null;
  /**
   * Total page views
   */
  viewCount?: number | null;
  /**
   * Number of content updates
   */
  updateCount?: number | null;
  featured?: boolean | null;
  /**
   * Estimated reading time in minutes
   */
  readingTime?: number | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cruises".
 */
export interface Cruise {
  id: number;
  title: string;
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  destination: number | Destination;
  nights?: number | null;
  durationText?: string | null;
  routeSummary?: string | null;
  cabinTypes?:
    | {
        label: string;
        price: number;
        maxPax?: number | null;
        id?: string | null;
      }[]
    | null;
  priceFrom?: number | null;
  currency?: string | null;
  ratingAverage?: number | null;
  ratingCount?: number | null;
  isFeatured?: boolean | null;
  sortWeight?: number | null;
  status: 'active' | 'seasonal' | 'sold-out' | 'paused';
  itinerary?:
    | {
        time?: string | null;
        activity?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  nationality?: string | null;
  /**
   * Linked Clerk user ID (set on first SSO login)
   */
  clerkUserId?: string | null;
  preferredContactChannel?: ('whatsapp' | 'email' | 'zalo' | 'phone') | null;
  /**
   * Internal CRM notes — not visible to customer
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  customer?: (number | null) | Customer;
  tour: number | Tour;
  numPax: number;
  preferredDate: string;
  specialRequest?: string | null;
  contactChannel?: ('whatsapp' | 'email' | 'zalo' | 'phone') | null;
  status: 'Pending' | 'Confirmed - Pay Later' | 'Confirmed - Paid' | 'Completed' | 'Cancelled';
  /**
   * Client-generated key for deduplication on submit
   */
  idempotencyKey: string;
  /**
   * Nullable — set in Phase 5
   */
  paymentMethod?: string | null;
  /**
   * Nullable — set in Phase 5
   */
  paymentStatus?: string | null;
  /**
   * Provider webhook event ID for idempotency — Phase 5
   */
  paymentProviderEventId?: string | null;
  internalNotes?: string | null;
  source?: ('direct' | 'free-tour-upsell' | 'blog-cta' | 'social' | 'ota') | null;
  /**
   * Append-only audit trail — do not edit manually
   */
  statusHistory?:
    | {
        from?: string | null;
        to: string;
        actor?: string | null;
        reason?: string | null;
        source?: string | null;
        createdAt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "custom-inquiries".
 */
export interface CustomInquiry {
  id: number;
  customer?: (number | null) | Customer;
  customerName: string;
  email: string;
  phone?: string | null;
  nationality?: string | null;
  whatsappOptIn?: boolean | null;
  planningStage?: string | null;
  referralSource?: string | null;
  travelCompanions?: string | null;
  occasion?: string | null;
  adults: number;
  children?: number | null;
  exactDatesKnown?: boolean | null;
  departureDate?: string | null;
  returnDate?: string | null;
  departureMonth?: string | null;
  estimatedDays?: number | null;
  accommodationLevels?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  themes?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  accompanimentType?: string | null;
  budgetPerPerson?: number | null;
  maxBudget?: number | null;
  selectedDestinations: (number | Destination)[];
  message?: string | null;
  source?: string | null;
  status: 'new' | 'contacted' | 'quoted' | 'closed' | 'spam';
  internalNotes?: string | null;
  idempotencyKey: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  role: string;
  photo?: (number | null) | Media;
  quote?: string | null;
  sortWeight?: number | null;
  status?: ('draft' | 'published') | null;
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  name: string;
  hotline?: string | null;
  whatsapp?: string | null;
  /**
   * Messenger m.me username (e.g. "tctravel") or full URL.
   */
  messenger?: string | null;
  salesEmail?: string | null;
  /**
   * Links shown in the sticky top bar and footer (Facebook, Instagram, language icons, etc.).
   */
  social?:
    | {
        platform: 'facebook' | 'instagram' | 'youtube' | 'tiktok' | 'whatsapp';
        url: string;
        /**
         * Accessible label, e.g. "TC Travel on Facebook".
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  footer?: {
    companyName?: string | null;
    legalText?: string | null;
    address?: string | null;
  };
  trust?: {
    reviewAverage?: number | null;
    reviewCount?: number | null;
    summary?: string | null;
  };
  /**
   * Toggle each homepage section on/off and override its copy. Leave a text field blank to keep the built-in default.
   */
  homepage?: {
    hero?: {
      /**
       * Show this section on the homepage.
       */
      enabled?: boolean | null;
      title?: string | null;
      subtitle?: string | null;
      body?: string | null;
      trustItems?:
        | {
            label: string;
            hint?: string | null;
            id?: string | null;
          }[]
        | null;
    };
    /**
     * Tour search form shown under the hero.
     */
    search?: {
      /**
       * Show this section on the homepage.
       */
      enabled?: boolean | null;
      eyebrow?: string | null;
      title?: string | null;
      subtitle?: string | null;
    };
    seasonalBanner?: {
      /**
       * Show this section on the homepage.
       */
      enabled?: boolean | null;
    };
    featuredTours?: {
      /**
       * Show this section on the homepage.
       */
      enabled?: boolean | null;
      eyebrow?: string | null;
      title?: string | null;
      subtitle?: string | null;
      actionLabel?: string | null;
      actionHref?: string | null;
    };
    cruises?: {
      /**
       * Show this section on the homepage.
       */
      enabled?: boolean | null;
      eyebrow?: string | null;
      title?: string | null;
      subtitle?: string | null;
      actionLabel?: string | null;
      actionHref?: string | null;
    };
    destinations?: {
      /**
       * Show this section on the homepage.
       */
      enabled?: boolean | null;
      eyebrow?: string | null;
      title?: string | null;
      subtitle?: string | null;
      actionLabel?: string | null;
      actionHref?: string | null;
    };
    freeTours?: {
      /**
       * Show the Free Tours section on the homepage.
       */
      sectionEnabled?: boolean | null;
      /**
       * Keep the /free-tours page reachable (off returns 404).
       */
      pageEnabled?: boolean | null;
      eyebrow?: string | null;
      title?: string | null;
      subtitle?: string | null;
      actionLabel?: string | null;
      actionHref?: string | null;
    };
    /**
     * External partner (OTA) section header. Providers are configured in the OTA group.
     */
    featuredExperiences?: {
      /**
       * Show this section on the homepage.
       */
      enabled?: boolean | null;
      eyebrow?: string | null;
      title?: string | null;
      subtitle?: string | null;
    };
    testimonials?: {
      /**
       * Show this section on the homepage.
       */
      enabled?: boolean | null;
    };
    team?: {
      /**
       * Show this section on the homepage.
       */
      enabled?: boolean | null;
      eyebrow?: string | null;
      title?: string | null;
      subtitle?: string | null;
      actionLabel?: string | null;
      actionHref?: string | null;
    };
    whyUs?: {
      /**
       * Show this section on the homepage.
       */
      enabled?: boolean | null;
      eyebrow?: string | null;
      title?: string | null;
      subtitle?: string | null;
      items?:
        | {
            icon?: ('compass' | 'shield' | 'wallet' | 'heart' | 'sparkle') | null;
            title: string;
            body: string;
            id?: string | null;
          }[]
        | null;
    };
    blog?: {
      /**
       * Show this section on the homepage.
       */
      enabled?: boolean | null;
      eyebrow?: string | null;
      title?: string | null;
      subtitle?: string | null;
      actionLabel?: string | null;
      actionHref?: string | null;
    };
    newsletter?: {
      /**
       * Show this section on the homepage.
       */
      enabled?: boolean | null;
      title?: string | null;
      subtitle?: string | null;
    };
  };
  /**
   * Tabs and dropdown options for the search box under the hero. Enable/disable the whole box in Homepage sections → search.
   */
  searchForm?: {
    /**
     * Header buttons. Leave empty for the default Tours / Halong / Mekong tabs.
     */
    tabs?:
      | {
          /**
           * e.g. "Halong Bay Cruises"
           */
          label: string;
          /**
           * Where the Search button sends the visitor.
           */
          target: 'tours' | 'cruises';
          id?: string | null;
        }[]
      | null;
    /**
     * Leave empty to use built-in defaults.
     */
    tourTypes?:
      | {
          label: string;
          /**
           * Tours.type slug, e.g. "paid-private"
           */
          value: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Leave empty to use built-in defaults.
     */
    tourDurations?:
      | {
          label: string;
          /**
           * "min-max" day range, e.g. "6-10" or "16-"
           */
          value: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Leave empty to use built-in defaults.
     */
    cruiseNights?:
      | {
          label: string;
          /**
           * Integer night count, e.g. "2"
           */
          value: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Leave empty to use built-in defaults.
     */
    styles?:
      | {
          label: string;
          /**
           * product-category slug, e.g. "culture"
           */
          value: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Configure external travel-partner (OTA) widgets. Add an affiliate URL template per provider to earn commission without a code change.
   */
  ota?: {
    /**
     * Master switch for all OTA widgets across the site.
     */
    enabled?: boolean | null;
    /**
     * Per-provider affiliate config. Empty URL template = generic search link.
     */
    providers?:
      | {
          key: 'getyourguide' | 'viator' | 'klook' | 'civitatis' | 'guruwalk';
          /**
           * Optional display name override.
           */
          label?: string | null;
          /**
           * Affiliate URL with a {city} token, e.g. https://www.getyourguide.com/s/?q={city}&partner_id=ABC123. Leave blank for the default search URL.
           */
          urlTemplate?: string | null;
          enabled?: boolean | null;
          id?: string | null;
        }[]
      | null;
    placements?: {
      /**
       * Homepage "Featured Experiences" section.
       */
      home?: {
        enabled?: boolean | null;
        /**
         * Which providers to show here. Leave empty to use the built-in default.
         */
        providers?: ('getyourguide' | 'viator' | 'klook' | 'civitatis' | 'guruwalk')[] | null;
        /**
         * Override the card heading (default: "More things to do in {city}").
         */
        heading?: string | null;
        blurb?: string | null;
      };
      /**
       * Destination detail pages.
       */
      destination?: {
        enabled?: boolean | null;
        /**
         * Which providers to show here. Leave empty to use the built-in default.
         */
        providers?: ('getyourguide' | 'viator' | 'klook' | 'civitatis' | 'guruwalk')[] | null;
        /**
         * Override the card heading (default: "More things to do in {city}").
         */
        heading?: string | null;
        blurb?: string | null;
      };
      /**
       * Tour detail pages.
       */
      tour?: {
        enabled?: boolean | null;
        /**
         * Which providers to show here. Leave empty to use the built-in default.
         */
        providers?: ('getyourguide' | 'viator' | 'klook' | 'civitatis' | 'guruwalk')[] | null;
        /**
         * Override the card heading (default: "More things to do in {city}").
         */
        heading?: string | null;
        blurb?: string | null;
      };
    };
  };
  /**
   * Control the /customize-tour page: enable it, and edit the planning stages and theme chips.
   */
  freeProposal?: {
    /**
     * Keep the /customize-tour page reachable (off returns 404).
     */
    enabled?: boolean | null;
    stages?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    themes?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    hero?: {
      eyebrow?: string | null;
      title?: string | null;
      subtitle?: string | null;
    };
  };
  blogMedia?: {
    videoEyebrow?: string | null;
    videoTitle?: string | null;
    videoSubtitle?: string | null;
    /**
     * YouTube URL or 11-char video ID. Empty hides the video section.
     */
    videoUrl?: string | null;
    galleryEyebrow?: string | null;
    gallerySubtitle?: string | null;
    /**
     * Photos shown in the gallery carousel. Empty hides the gallery section.
     */
    gallery?:
      | {
          image: number | Media;
          caption?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  name: string;
  location: 'header' | 'footer';
  status: 'draft' | 'published';
  items: {
    label: string;
    href?: string | null;
    target?: ('_self' | '_blank') | null;
    children?:
      | {
          label: string;
          href: string;
          target?: ('_self' | '_blank') | null;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: number;
  /**
   * Set for authenticated commenters; blank for public guest submissions
   */
  author?: (number | null) | User;
  /**
   * Public display name shown on the blog (falls back to author email)
   */
  authorName?: string | null;
  target:
    | {
        relationTo: 'tours';
        value: number | Tour;
      }
    | {
        relationTo: 'posts';
        value: number | Post;
      };
  content: string;
  /**
   * Optional 1-5 star rating left with a blog comment
   */
  rating?: number | null;
  status: 'pending' | 'approved' | 'hidden';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  customer: number | Customer;
  tour: number | Tour;
  booking?: (number | null) | Booking;
  rating: number;
  comment?: string | null;
  status: 'pending' | 'approved' | 'hidden';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions".
 */
export interface Promotion {
  id: number;
  name: string;
  code: string;
  description?: string | null;
  discountType: 'percentage' | 'fixed';
  discountValue: number;
  applicableTours?: (number | Tour)[] | null;
  applicableMarkets?: ('EU' | 'US' | 'AU' | 'Asia' | 'VN')[] | null;
  startDate: string;
  endDate: string;
  season?: ('summer' | 'winter' | 'year-round') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  booking: number | Booking;
  amount: number;
  currency: string;
  paymentMethod?: ('cash' | 'bank-transfer' | 'stripe' | 'vnpay' | 'momo') | null;
  status: 'pending' | 'processing' | 'completed' | 'failed' | 'refunded';
  /**
   * Payment provider event ID — used for webhook idempotency (Phase 5)
   */
  providerEventId?: string | null;
  providerPaymentId?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliate-clicks".
 */
export interface AffiliateClick {
  id: number;
  targetType: 'addon' | 'ota';
  targetId: string;
  targetUrl: string;
  /**
   * Path of the page where the click happened
   */
  source: string;
  referrer?: string | null;
  userAgent?: string | null;
  /**
   * One-way SHA-256 hash of the client IP (salted with PAYLOAD_SECRET)
   */
  ipHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "currencies".
 */
export interface Currency {
  id: number;
  /**
   * ISO 4217 code, e.g. USD, GBP, EUR, PHP.
   */
  code: string;
  /**
   * Full name, e.g. "British Pound".
   */
  name: string;
  /**
   * Display symbol, e.g. "$", "£", "€", "₫".
   */
  symbol: string;
  /**
   * Units of THIS currency per 1 unit of the base (default) currency. The base currency must be 1. Example: if base is USD and 1 USD = 0.79 GBP, set GBP to 0.79.
   */
  rateToBase: number;
  /**
   * Fraction digits shown. Use 0 for JPY/VND.
   */
  decimals: number;
  symbolPosition: 'before' | 'after';
  /**
   * Show this currency in the storefront selector.
   */
  active?: boolean | null;
  /**
   * The base currency that all tour prices are stored in. Exactly one currency should be the default, and its rate must be 1.
   */
  isDefault?: boolean | null;
  /**
   * Order in the selector dropdown (ascending).
   */
  sort?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'product-categories';
        value: number | ProductCategory;
      } | null)
    | ({
        relationTo: 'attractions';
        value: number | Attraction;
      } | null)
    | ({
        relationTo: 'destinations';
        value: number | Destination;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'tours';
        value: number | Tour;
      } | null)
    | ({
        relationTo: 'cruises';
        value: number | Cruise;
      } | null)
    | ({
        relationTo: 'car-rentals';
        value: number | CarRental;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'custom-inquiries';
        value: number | CustomInquiry;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'site-settings';
        value: number | SiteSetting;
      } | null)
    | ({
        relationTo: 'navigation';
        value: number | Navigation;
      } | null)
    | ({
        relationTo: 'comments';
        value: number | Comment;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'promotions';
        value: number | Promotion;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'affiliate-clicks';
        value: number | AffiliateClick;
      } | null)
    | ({
        relationTo: 'currencies';
        value: number | Currency;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  status?: T;
  r2Key?: T;
  publicUrl?: T;
  variants?: T;
  processingError?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories_select".
 */
export interface ProductCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  sortWeight?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attractions_select".
 */
export interface AttractionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  destination?: T;
  summary?: T;
  featuredImage?: T;
  categories?: T;
  sortWeight?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations_select".
 */
export interface DestinationsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  summary?: T;
  featuredImage?: T;
  heroImage?: T;
  region?: T;
  bestTimeToVisit?: T;
  hubIntro?: T;
  sortWeight?: T;
  featuredTours?: T;
  featuredCarRentals?: T;
  featuredGuides?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  description?: T;
  partnerType?: T;
  location?: T;
  commissionRate?: T;
  contactPerson?: T;
  phone?: T;
  email?: T;
  whatsapp?: T;
  rating?: T;
  isFeatured?: T;
  inquiryFormUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tours_select".
 */
export interface ToursSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  featuredImage?: T;
  gallery?: T;
  destination?: T;
  durationDays?: T;
  durationText?: T;
  routeSummary?: T;
  startEnd?: T;
  travelStyle?: T;
  guideLanguages?: T;
  mapImage?: T;
  highlightIntro?: T;
  highlights?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  inclusions?:
    | T
    | {
        item?: T;
        id?: T;
      };
  exclusions?:
    | T
    | {
        item?: T;
        id?: T;
      };
  groupSizeMin?: T;
  groupSizeMax?: T;
  categories?: T;
  attractions?: T;
  ratingAverage?: T;
  ratingCount?: T;
  isFeatured?: T;
  sortWeight?: T;
  operationType?: T;
  partner?: T;
  minPax?: T;
  currentPax?: T;
  tourType?: T;
  season?: T;
  isFeaturedInSeason?: T;
  status?: T;
  priceFrom?: T;
  currency?: T;
  pricingTiers?:
    | T
    | {
        label?: T;
        price?: T;
        minPax?: T;
        maxPax?: T;
        id?: T;
      };
  availableDates?:
    | T
    | {
        date?: T;
        id?: T;
      };
  itinerary?:
    | T
    | {
        time?: T;
        location?: T;
        distance?: T;
        title?: T;
        activity?: T;
        note?: T;
        included?:
          | T
          | {
              item?: T;
              id?: T;
            };
        hotelName?: T;
        hotelStars?: T;
        hotelRoom?: T;
        id?: T;
      };
  addOns?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cruises_select".
 */
export interface CruisesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  featuredImage?: T;
  gallery?: T;
  destination?: T;
  nights?: T;
  durationText?: T;
  routeSummary?: T;
  cabinTypes?:
    | T
    | {
        label?: T;
        price?: T;
        maxPax?: T;
        id?: T;
      };
  priceFrom?: T;
  currency?: T;
  ratingAverage?: T;
  ratingCount?: T;
  isFeatured?: T;
  sortWeight?: T;
  status?: T;
  itinerary?:
    | T
    | {
        time?: T;
        activity?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "car-rentals_select".
 */
export interface CarRentalsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  destination?: T;
  routeFrom?: T;
  routeTo?: T;
  vehicleType?: T;
  durationText?: T;
  priceFrom?: T;
  currency?: T;
  featuredImage?: T;
  gallery?: T;
  partner?: T;
  status?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  nationality?: T;
  clerkUserId?: T;
  preferredContactChannel?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  customer?: T;
  tour?: T;
  numPax?: T;
  preferredDate?: T;
  specialRequest?: T;
  contactChannel?: T;
  status?: T;
  idempotencyKey?: T;
  paymentMethod?: T;
  paymentStatus?: T;
  paymentProviderEventId?: T;
  internalNotes?: T;
  source?: T;
  statusHistory?:
    | T
    | {
        from?: T;
        to?: T;
        actor?: T;
        reason?: T;
        source?: T;
        createdAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "custom-inquiries_select".
 */
export interface CustomInquiriesSelect<T extends boolean = true> {
  customer?: T;
  customerName?: T;
  email?: T;
  phone?: T;
  nationality?: T;
  whatsappOptIn?: T;
  planningStage?: T;
  referralSource?: T;
  travelCompanions?: T;
  occasion?: T;
  adults?: T;
  children?: T;
  exactDatesKnown?: T;
  departureDate?: T;
  returnDate?: T;
  departureMonth?: T;
  estimatedDays?: T;
  accommodationLevels?:
    | T
    | {
        value?: T;
        id?: T;
      };
  themes?:
    | T
    | {
        value?: T;
        id?: T;
      };
  accompanimentType?: T;
  budgetPerPerson?: T;
  maxBudget?: T;
  selectedDestinations?: T;
  message?: T;
  source?: T;
  status?: T;
  internalNotes?: T;
  idempotencyKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  featuredImage?: T;
  content?: T;
  status?: T;
  destination?: T;
  guideCategory?: T;
  attractions?: T;
  sortWeight?: T;
  relatedTour?: T;
  relatedPosts?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  author?: T;
  viewCount?: T;
  updateCount?: T;
  featured?: T;
  readingTime?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  photo?: T;
  quote?: T;
  sortWeight?: T;
  status?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  hotline?: T;
  whatsapp?: T;
  messenger?: T;
  salesEmail?: T;
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  footer?:
    | T
    | {
        companyName?: T;
        legalText?: T;
        address?: T;
      };
  trust?:
    | T
    | {
        reviewAverage?: T;
        reviewCount?: T;
        summary?: T;
      };
  homepage?:
    | T
    | {
        hero?:
          | T
          | {
              enabled?: T;
              title?: T;
              subtitle?: T;
              body?: T;
              trustItems?:
                | T
                | {
                    label?: T;
                    hint?: T;
                    id?: T;
                  };
            };
        search?:
          | T
          | {
              enabled?: T;
              eyebrow?: T;
              title?: T;
              subtitle?: T;
            };
        seasonalBanner?:
          | T
          | {
              enabled?: T;
            };
        featuredTours?:
          | T
          | {
              enabled?: T;
              eyebrow?: T;
              title?: T;
              subtitle?: T;
              actionLabel?: T;
              actionHref?: T;
            };
        cruises?:
          | T
          | {
              enabled?: T;
              eyebrow?: T;
              title?: T;
              subtitle?: T;
              actionLabel?: T;
              actionHref?: T;
            };
        destinations?:
          | T
          | {
              enabled?: T;
              eyebrow?: T;
              title?: T;
              subtitle?: T;
              actionLabel?: T;
              actionHref?: T;
            };
        freeTours?:
          | T
          | {
              sectionEnabled?: T;
              pageEnabled?: T;
              eyebrow?: T;
              title?: T;
              subtitle?: T;
              actionLabel?: T;
              actionHref?: T;
            };
        featuredExperiences?:
          | T
          | {
              enabled?: T;
              eyebrow?: T;
              title?: T;
              subtitle?: T;
            };
        testimonials?:
          | T
          | {
              enabled?: T;
            };
        team?:
          | T
          | {
              enabled?: T;
              eyebrow?: T;
              title?: T;
              subtitle?: T;
              actionLabel?: T;
              actionHref?: T;
            };
        whyUs?:
          | T
          | {
              enabled?: T;
              eyebrow?: T;
              title?: T;
              subtitle?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
            };
        blog?:
          | T
          | {
              enabled?: T;
              eyebrow?: T;
              title?: T;
              subtitle?: T;
              actionLabel?: T;
              actionHref?: T;
            };
        newsletter?:
          | T
          | {
              enabled?: T;
              title?: T;
              subtitle?: T;
            };
      };
  searchForm?:
    | T
    | {
        tabs?:
          | T
          | {
              label?: T;
              target?: T;
              id?: T;
            };
        tourTypes?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        tourDurations?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        cruiseNights?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        styles?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
      };
  ota?:
    | T
    | {
        enabled?: T;
        providers?:
          | T
          | {
              key?: T;
              label?: T;
              urlTemplate?: T;
              enabled?: T;
              id?: T;
            };
        placements?:
          | T
          | {
              home?:
                | T
                | {
                    enabled?: T;
                    providers?: T;
                    heading?: T;
                    blurb?: T;
                  };
              destination?:
                | T
                | {
                    enabled?: T;
                    providers?: T;
                    heading?: T;
                    blurb?: T;
                  };
              tour?:
                | T
                | {
                    enabled?: T;
                    providers?: T;
                    heading?: T;
                    blurb?: T;
                  };
            };
      };
  freeProposal?:
    | T
    | {
        enabled?: T;
        stages?:
          | T
          | {
              value?: T;
              id?: T;
            };
        themes?:
          | T
          | {
              value?: T;
              id?: T;
            };
        hero?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              subtitle?: T;
            };
      };
  blogMedia?:
    | T
    | {
        videoEyebrow?: T;
        videoTitle?: T;
        videoSubtitle?: T;
        videoUrl?: T;
        galleryEyebrow?: T;
        gallerySubtitle?: T;
        gallery?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  name?: T;
  location?: T;
  status?: T;
  items?:
    | T
    | {
        label?: T;
        href?: T;
        target?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              target?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  author?: T;
  authorName?: T;
  target?: T;
  content?: T;
  rating?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  customer?: T;
  tour?: T;
  booking?: T;
  rating?: T;
  comment?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions_select".
 */
export interface PromotionsSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  description?: T;
  discountType?: T;
  discountValue?: T;
  applicableTours?: T;
  applicableMarkets?: T;
  startDate?: T;
  endDate?: T;
  season?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  booking?: T;
  amount?: T;
  currency?: T;
  paymentMethod?: T;
  status?: T;
  providerEventId?: T;
  providerPaymentId?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliate-clicks_select".
 */
export interface AffiliateClicksSelect<T extends boolean = true> {
  targetType?: T;
  targetId?: T;
  targetUrl?: T;
  source?: T;
  referrer?: T;
  userAgent?: T;
  ipHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "currencies_select".
 */
export interface CurrenciesSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  symbol?: T;
  rateToBase?: T;
  decimals?: T;
  symbolPosition?: T;
  active?: T;
  isDefault?: T;
  sort?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}